name: carpool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.5
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
